apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: guestbook-ui.info
    http:
      paths:
      - backend:
          serviceName: guestbook-ui
          servicePort: 80
        path: /