---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-data
data:
  HOGEHOGE: FUGAFUGA
  temp.txt: |
    hogehoge
    fugafuga
    foo bar baz
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-data
stringData:
  password: 1mbb1G968fb1CUg
  credential.txt: |
    credential data
    sWIEpx9wUdrVizVq
    UxuZ8kTeXvzyOWLQ
    7QVJIN1OI5FhxT9e