apiVersion: v1
kind: Pod
metadata:
  name: date-tail
spec:
  initContainers:
    - name: touch
      image: alpine
      command: ["sh", "-c"]
      args:
      - |
        echo Initialize...
        touch /var/log/date-tail/output.log
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/date-tail
  containers:
    - name: date
      image: alpine
      command: ["sh", "-c"]
      args:
      - |
        exec >> /var/log/date-tail/output.log
        echo -n 'Start at: '
        while true; do
          date
          sleep 1
        done
      volumeMounts:
        - mountPath: /var/log/date-tail
          name: log-volume
    - name: tail
      image: alpine
      command: ["sh", "-c"]
      args:
        - |
          tail -f /var/log/date-tail/output.log
      volumeMounts:
        - mountPath: /var/log/date-tail
          name: log-volume
  volumes:
    - name: log-volume
      hostPath:
        path: /data/date-tail
  terminationGracePeriodSeconds: 0

