namespace: "argocd"
bases:
  - ./sealed-secrets-controller.yaml # sealed-secrets
  - "github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.4.2"
resources:
  - ./sealed-secrets-key.yaml
  - ./application.yaml
  - ./argocd-github-private-key.yaml
patchesStrategicMerge:
  - ./argocd-cm.yaml

