apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    component: nginx
spec:
  replicas: 3
  # このselectorに指定した条件のpodを管理する
  selector:
    matchLabels:
      component: nginx
  # このReplicasetが作成するPodの定義
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
