apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-parameters-
spec:
  entrypoint: A
  arguments:
    parameters:
    - name: log-level
      value: INFO
  templates:
  - name: A
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["global-parameters cowsay!!!"]
      env:
      - name: LOG_LEVEL
        value: "{{workflow.parameters.log-level}}"